--zad1
select T_OSOBA.Imie || ' ' || T_OSOBA.Nazwisko OSOBA
from T_OSOBA
WHERE T_OSOBA.IMIE not like 'E%'
  and T_OSOBA.IMIE not like 'P%';

--zad2
SELECT T_PRODUKT.Nazwa, T_PRODUKT.Cena
from T_PRODUKT
where T_PRODUKT.CENA = (Select max(cena) from T_PRODUKT);

--zad3
SELECT T_OSOBA.IMIE || ' ' || T_OSOBA.Nazwisko
FROM T_OSOBA
WHERE NOT EXISTS(SELECT 1 FROM T_ZAKUP WHERE T_ZAKUP.KLIENT = T_OSOBA.ID);

--zad4.1
SELECT T_PRODUKT.Nazwa, T_PRODUKT.Cena
from T_PRODUKT
         INNER JOIN T_KATEGORIA ON T_PRODUKT.KATEGORIA = T_KATEGORIA.ID
WHERE T_PRODUKT.CENA > ALL (SELECT T2.CENA
                            FROM T_PRODUKT T2
                                     INNER JOIN T_KATEGORIA TK on TK.ID = T2.KATEGORIA
                            WHERE TK.NAZWA = 'fruit');

--zad4.2
SELECT T_PRODUKT.Nazwa, T_PRODUKT.Cena
from T_PRODUKT
         INNER JOIN T_KATEGORIA ON T_PRODUKT.KATEGORIA = T_KATEGORIA.ID
WHERE T_PRODUKT.CENA > ANY (SELECT min(T2.CENA)
                            FROM T_PRODUKT T2
                                     INNER JOIN T_KATEGORIA TK on TK.ID = T2.KATEGORIA
                            WHERE TK.NAZWA = 'vegetable');

--zad5
SELECT T_PRODUKT.NAZWA, TL.ILOSC, TK.NAZWA
FROM T_PRODUKT
         inner join T_KATEGORIA TK on TK.ID = T_PRODUKT.KATEGORIA
         inner join T_LISTAPRODUKTOW TL on T_PRODUKT.ID = TL.PRODUKT
         inner join T_ZAKUP TZ on TL.ZAKUP = TZ.ID
WHERE TZ.ID = 4
ORDER BY TL.ILOSC desc;

--zad6
SELECT T_OSOBA.IMIE || ' ' || T_OSOBA.NAZWISKO PRACOWNIK, T_STANOWISKO.NAZWA, T_ZATRUDNIENIE.OD
FROM T_OSOBA
         INNER JOIN T_PRACOWNIK ON T_OSOBA.ID = T_PRACOWNIK.ID
         INNER JOIN T_ZATRUDNIENIE ON T_PRACOWNIK.ID = T_ZATRUDNIENIE.PRACOWNIK
         INNER JOIN T_STANOWISKO ON T_ZATRUDNIENIE.STANOWISKO = T_STANOWISKO.ID
WHERE T_ZATRUDNIENIE.DO IS NULL
ORDER BY T_ZATRUDNIENIE.OD ASC;

--zad7
SELECT T_OSOBA.IMIE || ' ' || T_OSOBA.NAZWISKO PRACOWNIK, TO2.Nazwisko Szef
from T_OSOBA
         INNER JOIN T_PRACOWNIK ON T_OSOBA.ID = T_PRACOWNIK.ID
         INNER JOIN T_ZATRUDNIENIE ON T_PRACOWNIK.ID = T_ZATRUDNIENIE.PRACOWNIK
         INNER JOIN T_OSOBA TO2 ON T_PRACOWNIK.SZEF = TO2.ID
    AND T_ZATRUDNIENIE.DO IS NULL
UNION
SELECT T_OSOBA.IMIE || ' ' || T_OSOBA.NAZWISKO PRACOWNIK, 'no boss'
FROM T_OSOBA
         INNER JOIN T_PRACOWNIK ON T_OSOBA.ID = T_PRACOWNIK.ID
         INNER JOIN T_ZATRUDNIENIE ON T_PRACOWNIK.ID = T_ZATRUDNIENIE.PRACOWNIK
WHERE T_PRACOWNIK.SZEF IS NULL
  AND T_ZATRUDNIENIE.DO IS NULL;

--zad8
SELECT T_PRODUKT.NAZWA, COUNT(T_ZAKUP.Id)
FROM T_PRODUKT
         INNER JOIN T_LISTAPRODUKTOW TL on T_PRODUKT.ID = TL.PRODUKT
         INNER JOIN T_ZAKUP ON TL.ZAKUP = T_ZAKUP.ID
         INNER JOIN T_KATEGORIA ON T_PRODUKT.KATEGORIA = T_KATEGORIA.ID
WHERE T_KATEGORIA.NAZWA = 'fruit'
GROUP BY T_PRODUKT.NAZWA;

--zad9
select T_OSOBA.Imie || ' ' || T_OSOBA.NAZWISKO, count(T_ZAKUP.ID)
FROM T_OSOBA
         INNER JOIN T_ZAKUP ON T_OSOBA.ID = T_ZAKUP.KLIENT
WHERE EXTRACT(YEAR from T_ZAKUP.DATA) IN (2020, 2021)
group by T_OSOBA.Imie || ' ' || T_OSOBA.NAZWISKO;

--zad10
select T_OSOBA.Imie || ' ' || T_OSOBA.NAZWISKO, SUM(T_LISTAPRODUKTOW.ILOSC)
FROM T_OSOBA
         INNER JOIN T_ZAKUP ON T_OSOBA.ID = T_ZAKUP.KLIENT
         INNER JOIN T_LISTAPRODUKTOW on T_ZAKUP.ID = T_LISTAPRODUKTOW.ZAKUP
         INNER JOIN T_PRODUKT on T_LISTAPRODUKTOW.PRODUKT = T_PRODUKT.ID
         INNER JOIN T_KATEGORIA ON T_PRODUKT.KATEGORIA = T_KATEGORIA.ID
WHERE T_KATEGORIA.NAZWA = 'fish'
group by T_OSOBA.Imie, T_OSOBA.NAZWISKO
HAVING SUM(T_LISTAPRODUKTOW.ILOSC) > 20;

--zad11
SELECT T_PRODUKT.NAZWA, SUM(TL.ILOSC), TK.NAZWA
FROM T_PRODUKT
         INNER JOIN S27523.T_KATEGORIA TK on T_PRODUKT.KATEGORIA = TK.ID
         INNER JOIN S27523.T_LISTAPRODUKTOW TL on T_PRODUKT.ID = TL.PRODUKT
         INNER JOIN T_ZAKUP ON TL.ZAKUP = T_ZAKUP.ID
         INNER JOIN T_OSOBA ON T_ZAKUP.KLIENT = T_OSOBA.ID
WHERE T_OSOBA.Id in (SELECT T_PRACOWNIK.SZEF
                     FROM T_PRACOWNIK
                              inner join T_OSOBA T02 ON T_PRACOWNIK.ID = T02.ID
                     WHERE T02.IMIE = 'Peter'
                       and T02.NAZWISKO = 'Paches')
group by T_PRODUKT.NAZWA, TK.NAZWA
ORDER BY SUM(TL.ILOSC) ASC;

--zad12
SELECT p.NAZWA, SUM(lp.ILOSC * p.CENA) WARTOSC
FROM T_PRODUKT p
         JOIN T_LISTAPRODUKTOW lp ON p.ID = lp.PRODUKT
         JOIN T_ZAKUP z ON lp.ZAKUP = z.ID
         JOIN T_OSOBA o ON z.KLIENT = o.ID
WHERE o.IMIE = 'Chris'
  AND o.NAZWISKO = 'Cnemus'
GROUP BY p.NAZWA;


--zad13
Select t_osoba.imie, t_osoba.nazwisko, sum(T_PRODUKT.cena * T_LISTAPRODUKTOW.Ilosc)
from T_OSOBA
         inner join T_ZAKUP on T_OSOBA.ID = T_ZAKUP.KLIENT
         inner join T_LISTAPRODUKTOW on T_ZAKUP.ID = T_LISTAPRODUKTOW.ZAKUP
         inner join T_PRODUKT on T_LISTAPRODUKTOW.PRODUKT = T_PRODUKT.ID
group by t_osoba.imie, t_osoba.nazwisko
having sum(T_PRODUKT.cena * T_LISTAPRODUKTOW.Ilosc) > 50;